fail_fast: true
minimum_pre_commit_version: 4.3.0
repos:
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validate Commit Message
        entry: >
          bash -c "if ! grep -iqE '^(feat|bugfix|hotfix|chore)' \"$1\"; then
            echo 'Invalid commit message: must start with feat|bugfix|hotfix|chore';
            exit 1;
          fi" --
        language: system
        stages: [commit-msg]

      - id: pytest-check
        name: Pytest-check
        entry: pytest pyker
        language: system
        pass_filenames: false
        always_run: true

      - id: check-sensitive-information
        name: Check for Sensitive Information
        # This will only print matches, but commits will pass if nothing sensitive is found.
        entry: bash -c 'grep -iE "password|api_key|secret_key" "$@" || true' --
        language: system
        types: [python]

      # - id: generate-docs
      #   name: Generate Documentation
      #   entry: "python scripts/generate_docs.py"
      #   language: python
      #   files: \.py

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
