fail_fast: true
minimum_pre_commit_version: 4.3.0
repos:
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validate Commit Message
        entry: >
          bash -c "if ! grep -iqE '^(feat|bugfix|hotfix|chore)' \"$1\"; then
            echo 'Invalid commit message: must start with feat|bugfix|hotfix|chore';
            exit 1;
          fi" --
        language: system
        stages: [commit-msg]

      - id: pytest-check
        name: Pytest-check
        entry: pytest pyker
        language: system
        pass_filenames: false
        always_run: true

      - id: check-sensitive-information
        name: Check for Sensitive Information
        # This will only print matches, but commits will pass if nothing sensitive is found.
        entry: >
          bash -c 'grep -iE "password|api_key|secret_key" "$@" && { echo "Sensitive info detected"; exit 1; }' --
        language: system
        types: [python]

      - id: generate-docs
        name: Generate Documentation
        entry: python pyker/scripts/generate_docs.py
        language: python
        pass_filenames: false
        always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff # linter
        args: [--fix]
      - id: ruff-format # formatter


  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.5.1
  #   hooks:
  #     - id: mypy
  #       args: ["--config-file=pyker/mypy.ini", "pyker"]
  #       types: [python]
  #       env:
  #         MYPYPATH: pyker
