fail_fast: true
minimum_pre_commit_version: 4.3.0
repos:
  - repo: local
    hooks:
      - id: validate-commit-message
        name: Validate Commit Message
        entry: >
          bash -c "if ! grep -iqE '^(feat|bugfix|hotfix|chore)' \"$1\"; then
            echo 'Invalid commit message: must start with feat|bugfix|hotfix|chore';
            exit 1;
          fi" --
        language: system
        stages: [commit-msg]

      - id: pytest-check
        name: Pytest-check
        entry: pytest pyker
        language: system
        pass_filenames: false
        always_run: true

      - id: generate-docs
        name: Generate Documentation
        entry: python pyker/scripts/generate_docs.py
        language: python
        pass_filenames: false
        always_run: true

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff # linter
        args: [--fix]
      - id: ruff-format # formatter

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.379
    hooks:
      - id: pyright
        additional_dependencies:
          [
            beartype,
            einops,
            jax,
            jaxtyping,
            optax,
            pytest,
            typing_extensions,
            wadler_lindig,
          ]

  # - repo: https://github.com/returntocorp/semgrep
  #   rev: v1.92.0 # latest stable Semgrep
  #   hooks:
  #     - id: semgrep
  #       name: Semgrep Security Audit
  #       args: ["--config", "p/security-audit"]
